### ISSUE TITLE
Pressing "Enter" in a form does not validate the form

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#132]
When filling a form *e.g.* for creating a box, pressing "Enter" does not validate the form, it discards it. We should have "Esc" discard the form and "Enter" validate it.

**Comment by strategos-nzr** [comment]
![image](https://github.com/QuantStack/jupytercad/assets/106568776/29ff4a72-1d83-42bc-9791-22e60b378de6)

It is the same for 'submit' buttons as well. 

Also in the sketcher UI there is no way (even with escape) to re-select or de-select points or sketch tools.

Is it possible to import the FreeCAD gui and save work?

**Comment by trungleduc** [comment]
IIRC you can double click to remove the points

**Comment by strategos-nzr** [comment]
on my machine (windows) its right click, which works most of the time

Is there a way to enter into a completed sketch? I only see the option to make a new sketch.

**Comment by SylvainCorlay** [comment]
This seems to be fixed on my end.

**Comment by arjxn-py** [comment]
Yeah, fixed on my end too
