### ISSUE TITLE
Plugin system for supported types

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/jupytercad#215]
We should implement a "plugin" system for supported types in JupyterCad.

This would take the form of separate Python packages that expose the right entry points `jupytercad-freecad`, `jupytercad-step`, `jupytercad-salome` etc.

**Comment by trungleduc** [comment]
I think `STEP` (and other opencascade supported formats like IGES, STL) can be in the core package.

**Comment by martinRenou** [comment]
Sounds good 👍🏽 we could have separate packages only for file types that require a special dependency

**Comment by trungleduc** [comment]
Done
