### ISSUE TITLE
Switching tabs does not update the main view properly

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/jupytercad#236]
[Screencast from 2023-12-13 16-59-43.webm](https://github.com/jupytercad/jupytercad/assets/21197331/0768ee89-b219-4511-ba2d-5aa9b28dd6fa)

**Comment by trungleduc** [comment]
Maybe it is related to the STEP file since it does not happen with 2 JCAD files

https://github.com/jupytercad/jupytercad/assets/4451292/c1f7b396-11ab-4c05-b19d-248e6ff352bb

**Comment by martinRenou** [comment]
My first guess is that whenever a DISPLAY_SHAPE message is sent from the worker, all viewers are receiving the message

**Comment by trungleduc** [comment]
ah yes, I was too lazy to switch to main. Maybe we can wait for #230, I'm finishing it soon, and hopefully, this issue can be fixed.

**Comment by trungleduc** [comment]
it was done already :D
