### ISSUE TITLE
2.0.0 release plan

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#253]
1.0.0 was just out and we're already on making breaking changes with the [jupyter-collaboration v2 update](https://github.com/jupytercad/jupytercad/pull/239).

I will be making a 1.x branch so we can continue making patch releases on 1.x if needed.

**Comment by arjxn-py** [comment]
Hi @martinRenou, since `v2.0.0` is already released - Is this issue still relevant?

**Comment by martinRenou** [comment]
It's not thank you!
