### ISSUE TITLE
RFD: Proposal to Add Keybindings for Additional JupyterCAD Commands

### ISSUE THREAD

**Issue by arjxn-py** [jupytercad/JupyterCAD#396]
Currently, JupyterCAD supports keybindings for a few essential commands such as undo, redo, and removeObject. However, there are several other commands in JupyterCAD that would benefit from having dedicated keybindings to enhance UX.

Proposed Keybindings(Draft): 

- **New Sketch:** `Ctrl + Shift + N`
- **New Box:** `Ctrl + Shift + B`
- **New Cylinder:** `Ctrl + Shift + C`
- **New Sphere:** `Ctrl + Shift + S`
- **New Cone:** `Ctrl + Shift + E`
- **New Torus:** `Ctrl + Shift + T`
- **Cut:** `Ctrl + X`
- **Extrusion:** `Ctrl + Shift + E`
- **Union:** `Ctrl + U`
- **Intersection:** `Ctrl + I`
- **Chamfer:** `Ctrl + Shift + F`
- **Fillet:** `Ctrl + F`
- **Update Axes:** `Ctrl + Shift + A`
- **Update Exploded View:** `Ctrl + Shift + V`
- **Update Camera Settings:** `Ctrl + Shift + K`
- **Update Clip View:** `Ctrl + Shift + L`
- **Export Jcad:** `Ctrl + Shift + X`

**Comment by arjxn-py** [comment]
> * **New Box:** `Ctrl + Shift + B`
> * **New Cylinder:** `Ctrl + Shift + C`
> * **New Sphere:** `Ctrl + Shift + S`
> * **New Cone:** `Ctrl + Shift + E`
> * **New Torus:** `Ctrl + Shift + T`

I think these may also be fine to skip

**Comment by trungleduc** [comment]
Thanks for the suggestion. I think we should keep it consistent by prefixing all shortcuts with Ctrl + Shift and should avoid collision with JupyterLab shortcuts 

![kb](https://github.com/user-attachments/assets/ea4331dc-16ac-4f49-95c8-f5419e52834a)

**Comment by trungleduc** [comment]
> > * **New Box:** `Ctrl + Shift + B`
> > * **New Cylinder:** `Ctrl + Shift + C`
> > * **New Sphere:** `Ctrl + Shift + S`
> > * **New Cone:** `Ctrl + Shift + E`
> > * **New Torus:** `Ctrl + Shift + T`
> 
> I think these may also be fine to skip

I have no issues keeping these shortcuts
