### ISSUE TITLE
BUG: Error when Running JupyterCAD through `jupyter cad` Command

### ISSUE THREAD

**Issue by arjxn-py** [jupytercad/JupyterCAD#399]
When running JupyterCAD through the `jupyter cad` command in the terminal, the following errors are encountered in the browser logs, and the JupyterCAD editor fails to open:

```
Error: Shared module @jupyterlab/codeeditor doesn't exist in shared scope default
```
```
Error: Shared module @jupyterlab/completer doesn't exist in shared scope default
```
However, this issue does not occur when JupyterCAD is accessed through the `jupyter lab` command. In that case, the editor opens successfully without any errors.

**Comment by martinRenou** [comment]
This may just be about adding `@jupyterlab/codeeditor` and `@jupyterlab/completer` as dependencies for https://github.com/jupytercad/JupyterCAD/blob/main/python/jupytercad_app/package.json

**Comment by trungleduc** [comment]
and also here https://github.com/jupytercad/JupyterCAD/blob/main/python/jupytercad_app/src/sharedscope.ts

**Comment by arjxn-py** [comment]
Thanks both!
I'll be on it later today.
