### ISSUE TITLE
Improve the UX of the clip-plane and wireframe buttons

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#406]
## Problems

Today, the clip-plane toolbar button shows a dialog to select two options:
- selected
- show Clip Plane

In the other side, the wireframe button does not show a dialog and directly apply the wireframe effect. Though once toggled, there is no visual indication in the toolbar that the button has been toggled.

Also, refreshing the page or reopening the file does not keep the clip-plane or wireframe states. We could fix this by saving the states in the schema.

## Suggestions

- We could make the behavior more homogeneous by making the clip-plane toolbar button not showing a dialog and directly toggling the clip-plane effect (we would always show the clip-plane in the 3D scene by default).
- We should show a visual indication in the toolbar that toggle buttons are toggled
- We should save the states of the clip-plane and wireframe effect in the schema

**Comment by arjxn-py** [comment]
Thanks @martinRenou, it is well defined. I'll be happy to look into it 🚀
