### ISSUE TITLE
Deleting operators does not restore visibility of components

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#426]
When deleting e.g. a Union operator, we may want either make the components of the union become visible again.

**Comment by SylvainCorlay** [comment]
I am tagging this as a "question" because I am not sure what the desired behavior should be. Maybe we should look at what other editors do.

**Comment by arjxn-py** [comment]
> I am tagging this as a "question" because I am not sure what the desired behavior should be. Maybe we should look at what other editors do.

Thanks @SylvainCorlay, I at the moment do not have a strong opinion on this but I'll be happy to see how FreeCAD handles it and report back :)

**Comment by martinRenou** [comment]
> We may want to replicate the same in JCAD too

Sounds good!

**Comment by SylvainCorlay** [comment]
> We may want to replicate the same in JCAD too

I agree that replicating the FreeCAD behavior is probably what we want here.

**Comment by martinRenou** [comment]
We now have a `dependencies` property for all objects: https://github.com/jupytercad/JupyterCAD/blob/main/packages/schema/src/schema/jcad.json#L110

This could be used by setting `visible` back to True for all the `dependencies` objects as soon as the operator is removed.
