### ISSUE TITLE
"Color: should be a string" error in operator form

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#427]
When creating e.g. a union operator, I see the warning "Color: should be a string" in the form for the parameters of the operator.

I suppose there could be some default value assigned to the field so that it does not trigger an error.

<img width="805" alt="Screenshot 2024-09-16 at 21 07 36" src="https://github.com/user-attachments/assets/78173336-c967-40eb-9fdc-c041d99e7c41">

**Comment by arjxn-py** [comment]
This was also reported in https://github.com/jupytercad/JupyterCAD/pull/413#issuecomment-2348806223 but we couldn't reproduce it further 🫤 

I shall try looking into this more, should be an easy fix as far as I anticipate once reproduced. Thanks for opening this.

> I suppose there could be some default value assigned to the field so that it does not trigger an error.

Yes, it basically inherits the color of the base object which is being operated on.

**Comment by arjxn-py** [comment]
@SylvainCorlay, can you maybe confirm how you got this error: 
- You must have created two objects
- Then straight up clicked on any operator button. (Did you select any of the object before clicking on the operator button?)

**Comment by arjxn-py** [comment]
> Did you select any of the object before clicking on the operator button?

I ask as I could produce this another error when I haven't selected any object even once (related but not exactly this): 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
```

I think this one error is because in case of never selected `model.localState?.selected` should be undefined.


Having said that this is a different error, I'd once again request you to try reproducing `Color: should be a string` error and maybe give some inference or observation that can help further. Apologies & Thanks.

**Comment by SylvainCorlay** [comment]
> Having said that this is a different error, I'd once again request you to try reproducing Color: should be a string error and maybe give some inference or observation that can help further. Apologies & Thanks.

This seems to occur when opening an old jcad file dating from before colors were part of the model. The color is missing in the first object of the union.

We may decide to ignore this issue at this point.

**Comment by arjxn-py** [comment]
> We may decide to ignore this issue at this point.

Sounds good to me, As it's not affecting new files.
