### ISSUE TITLE
Remove old axes helper

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#442]
Now that we have a nice and interactive axes helper #440 we should get rid of the old axes helper and the associated toolbar button from the codebase

**Comment by trungleduc** [comment]
I think the old axes helper is not only about controlling the camera like the view helper. It also helps positioning the object in its coordinate space.

**Comment by martinRenou** [comment]
Ok, so would you be up for keeping it?

**Comment by trungleduc** [comment]
yes

**Comment by martinRenou** [comment]
Ok then let's keep it! Thanks for your comment
