### ISSUE TITLE
Open `.jcad` files with the `JSON` viewer

### ISSUE THREAD

**Issue by jtpio** [jupytercad/JupyterCAD#454]
Just like `.ipynb` files, it would be great to be able to open `.jcad` files with the JSON editor:

![Image](https://github.com/user-attachments/assets/e3e4b9e3-91fb-43f4-8c0f-ad3f66839014)

**Comment by SylvainCorlay** [comment]
I "assigned" it to Greg who is apparently doing it for JupyterGIS, so it should be a simple thing to do it in JupyterCAD.
