### ISSUE TITLE
Redo keyboard short

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#458]
The redo keyboard shortcut should probably be consistent with that of the notebook editor and with the shortcut indicated in the "Edit" topbar menu, that is ⇧ ⌘ Z on OSX.

![Image](https://github.com/user-attachments/assets/6eeb65da-7a39-4dc5-8001-39a64981c46e)

**Comment by martinRenou** [comment]
For the record, this is where the keybinding is defined https://github.com/jupytercad/JupyterCAD/blob/main/packages/base/src/keybindings.json#L9

**Comment by arjxn-py** [comment]
I shall look into how can i have different keybinding for OSX and Windows, Do you know already by any chance?

**Comment by SylvainCorlay** [comment]
I think that we should be as close as possible to the notebook user experience for this.

**Comment by arjxn-py** [comment]
> I think that we should be as close as possible to the notebook user experience for this.

I agree, and will be On my way! to see how they're handling it upstream. And I believe it shall not be an issue anymore to have the same keybinding for `redo` both in normal notebook or jcad file as conflict issue shall resolve in #451

**Comment by arjxn-py** [comment]
I couldn't find `Ctrl Y` or `Accel Y` for redo in jupyterlab's code, should I just update this to `Accel Shift Z` in that case?

**Comment by martinRenou** [comment]
Indeed JupyterLab is never using `Ctrl Y` for redo, let's stay aligned with JupyterLab
