### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#462]
Opening this for discussion.

@IsabelParedes made some nice logo designs 🚀 

@trungleduc @SylvainCorlay @arjxn-py please tell us your thoughts about them!

I have a personal preference for the green/yellow one.

Here there are:

# Blue

![Image](https://github.com/user-attachments/assets/3689e77d-22ca-4b88-9c99-93a3fb3af66c)

# Red

![Image](https://github.com/user-attachments/assets/fee96c90-1059-4242-a97a-36f3be48fe0b)

# Green/Yellow

![Image](https://github.com/user-attachments/assets/5ea332a0-d7af-4d93-9f8e-6e077b542fc3)

# Orange

![Image](https://github.com/user-attachments/assets/8f06698d-226a-47d4-a5fb-7873e0939488)

**Comment by trungleduc** [comment]
Blue one for me

**Comment by IsabelParedes** [comment]
Here are some python color logos as @arjxn-py suggested :)

<img src="https://github.com/user-attachments/assets/a86f448d-72a3-4509-8e6f-d3f8a660743a" width=20%>
<img src="https://github.com/user-attachments/assets/46d373be-1cc8-44c2-975e-a45eaa53ec3f" width=20%>
<img src="https://github.com/user-attachments/assets/61c5c381-3245-420c-ba2b-2e9e83624365" width=20%>
<img src="https://github.com/user-attachments/assets/259433b1-7a7e-43b4-b387-ff0279440d35" width=20%>

**Comment by arjxn-py** [comment]
Thanks @IsabelParedes, these are super awesome 🚀 
I really like first and third starting from left. 

Here's how they look, in their respective order:

![Image](https://github.com/user-attachments/assets/6072c817-2dde-4dc0-99af-3f7a54d89fc5)

![Image](https://github.com/user-attachments/assets/09d1091c-8db5-4a60-ba28-f57a0b983c6f)

![Image](https://github.com/user-attachments/assets/7df57405-c297-4eaa-b354-4aa52bf6b8a6)

![Image](https://github.com/user-attachments/assets/d2213f1f-a2cf-498b-9889-196d57f1e6de)

**Comment by SylvainCorlay** [comment]
This is really cool!

**Comment by SylvainCorlay** [comment]
We probably still want to use the css styling of the svg in the file browser so that the logo becomes white when the corresponding line is highlighted.

**Comment by trungleduc** [comment]
> Here are some python color logos as [@arjxn-py](https://github.com/arjxn-py) suggested :)
> 
> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/23283243/374939847-a86f448d-72a3-4509-8e6f-d3f8a660743a.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDcyOTQsIm5iZiI6MTcyODU0Njk5NCwicGF0aCI6Ii8yMzI4MzI0My8zNzQ5Mzk4NDctYTg2ZjQ0OGQtNzJhMy00NTA5LThlNmYtZDNmOGE2NjA3NDNhLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOWJmMjA1YWRjOWUxNGZjNjMyYmJhYjlkMGMzM2ZkMzVjMDJmNmQ5NjI1NmFiMDhlNjAxYzc3MzJiNzJjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FbnbHPEXYEhbhX0bQN0uM0vFkTCdSQ9zxrLvmU7UQXo"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/23283243/374939754-46d373be-1cc8-44c2-975e-a45eaa53ec3f.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDcyOTQsIm5iZiI6MTcyODU0Njk5NCwicGF0aCI6Ii8yMzI4MzI0My8zNzQ5Mzk3NTQtNDZkMzczYmUtMWNjOC00NGMyLTk3NWUtYTQ1ZWFhNTNlYzNmLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1Mjg0MWI2OTA2NjM4MjIzN2QyNjY0Yjc0OGEwM2IwODViMjcyZTFiMGI3MGY4YzllOWMwN2YzNjBhZmY2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1niSA5VhWAEsoEFq1PRn2aFOuBBOmIKJb6yhvBcJCtA"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/23283243/374939893-61c5c381-3245-420c-ba2b-2e9e83624365.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDcyOTQsIm5iZiI6MTcyODU0Njk5NCwicGF0aCI6Ii8yMzI4MzI0My8zNzQ5Mzk4OTMtNjFjNWMzODEtMzI0NS00MjBjLWJhMmItMmU5ZTgzNjI0MzY1LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzdjYzQwMmNjNjQyNzk0NGFjNGNjMTJkNWQxYjQ5NTRkNjY1MDJlYzliNTIxMDI3MmJlM2M3NjcxMDUwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1_6Y2BrJPF1SVB65zRfX8xUneuEWtmQTb-VmGE3SoiA"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/23283243/374939920-259433b1-7a7e-43b4-b387-ff0279440d35.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDcyOTQsIm5iZiI6MTcyODU0Njk5NCwicGF0aCI6Ii8yMzI4MzI0My8zNzQ5Mzk5MjAtMjU5NDMzYjEtN2E3ZS00M2I0LWIzODctZmYwMjc5NDQwZDM1LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MWRhYzYzZTVmMmU2ZjZmZmYwY2JmZmY0YzNiZDZjNjRlZWZiNGQ1OGZhYWZkZGRjZDg3Zjg5ZmQ4NjNjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GrSOAYRwJKif_jiIJv0z5d3pPpc7gLlTk3WHmz-ga2U">

it looks great!

**Comment by trungleduc** [comment]
> Thanks [@IsabelParedes](https://github.com/IsabelParedes), these are super awesome 🚀 I really like first and third starting from left. But if i have to choose one my preference would be first as it's more identifiable when small file icon due to the color difference between gears.

Does it work well in the dark theme?

**Comment by arjxn-py** [comment]
Yes @trungleduc, it looks good to me. What do you think?
![Image](https://github.com/user-attachments/assets/5c5ca860-3eb5-4149-9e80-4c88e7f7a2b0)
![Image](https://github.com/user-attachments/assets/6e2eaa3c-59f4-4aee-a96a-ed15fc12749e)
![Image](https://github.com/user-attachments/assets/da379d24-ace8-45fe-bd51-fff668cf3f46)
![Image](https://github.com/user-attachments/assets/629c014a-7e29-4cab-b6a2-632c97fd86b0)

**Comment by martinRenou** [comment]
Shall we go with the Python color palette then? I'm 👍🏽 for it, with a slight preference for the first screenshot from Arjun's comment right above.

**Comment by arjxn-py** [comment]
> Shall we go with the Python color palette then? I'm 👍🏽 for it, with a slight preference for the first screenshot from Arjun's comment right above.

Sounds good to me :)
