### ISSUE TITLE
Reduce field of view of the camera?

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#464]
@trungleduc This is more of a question, I am wondering why we've been using a field of view of 90 [since the very beginning of JupyterCAD](https://github.com/jupytercad/JupyterCAD/blame/74528e4744c3a5dfcc8ce822d550ed61c1c1d33d/src/mainview.tsx#L133)?

This is looking a bit off to me. I would have a personal preference for using the default value of 50 which looks more natural.

**Comment by trungleduc** [comment]
I can not recall anymore, maybe it's just a random value. Please go ahead and update it
