### ISSUE TITLE
RTC is broken on the main branch

### ISSUE THREAD

**Issue by trungleduc** [jupytercad/JupyterCAD#471]
With the latest changes in `jupyter-collaboration`, the RTC features do not work anymore, which causes failed UI tests.

**Comment by SylvainCorlay** [comment]
cc @davidbrochart

**Comment by SylvainCorlay** [comment]
It seems to be also preventing the JupyterLite deployment.

**Comment by trungleduc** [comment]
> It seems to be also preventing the JupyterLite deployment.

Yes, although JupyterLite itself should work since it does not depend on jupyter-collaboration, we require UI test passing before deploying JupyterLite

**Comment by davidbrochart** [comment]
I didn't look at the issue yet, but my first bet would be that jupyter-collaboration v3.0.0b8 has a new package `@jupyter/collaborative-drive` from which you import:
```ts
import {
  ICollaborativeDrive,
  ISharedModelFactory,
  SharedDocumentFactory
} from '@jupyter/collaborative-drive';
```
Instead of importing from `@jupyter/docprovider`.
