### ISSUE TITLE
Merge JupyterCAD "Object Properties"  panel with Notebook Cell Properties panel

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#476]
Both panels have a very similar UI and are (at least partially) based on `react-jsonschema-form` to produce the content.

I wonder if (given some changes upstream in this panel), we could reuse it for JupyterCAD.

**Comment by SylvainCorlay** [comment]
Thinking more about this. The solution might actually be to create a more generic property inspector that could be usable by the notebook instead.

**Comment by trungleduc** [comment]
Closed in favor of  https://github.com/jupytercad/JupyterCAD/pull/554
