### ISSUE TITLE
Changing theme in `jupyter cad` makes the scene blank

### ISSUE THREAD

**Issue by arjxn-py** [jupytercad/JupyterCAD#480]
https://github.com/user-attachments/assets/cf27756c-1311-4914-bac9-386b3987351d

**Comment by SylvainCorlay** [comment]
This is also the case in the JupyterLab extension.

**Comment by SylvainCorlay** [comment]
Note: it seems to re-appear whenever we do something that triggers a redraw like resizing the viewer panel.

**Comment by arjxn-py** [comment]
> Note: it seems to re-appear whenever we do something that triggers a redraw like resizing the viewer panel.

Thanks for letting know, alright this also seems to need a pinch of resize event.
