### ISSUE TITLE
JupyterCAD icon should be highlighted in the file browser when the file is selected

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#484]
I presume this would be achieved by adding the right CSS classes to the SVG files.

Screenshots below show the change os style of the selected file with a JCAD file vs a notebook.

![Image](https://github.com/user-attachments/assets/bba10096-9072-4f7c-91d1-bf0fd716cac6) ![Image](https://github.com/user-attachments/assets/a98015ae-94bc-4ea3-9246-243a159133c4)

**Comment by SylvainCorlay** [comment]
Related to https://github.com/jupytercad/JupyterCAD-FreeCAD/issues/14.

**Comment by martinRenou** [comment]
We may not need to take any action on this if we change the design of the logo and the new logo fits nicer with the blue background.

Let's see if we need to take any action once that new logo is settled.

**Comment by SylvainCorlay** [comment]
> We may not need to take any action on this if we change the design of the logo and the new logo fits nicer with the blue background.

It makes sense to wait for the new logo. Although even with the new logo, we should probably apply the selected style like for all other core Jupyter file types.
