### ISSUE TITLE
Default primitive dimensions should be comparable

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#486]
The default diameter of a sphere is 10, while the default dimensions of a box is 1x1x1.

I think that we should use comparable size for primitives.

![Image](https://github.com/user-attachments/assets/54b9ff9b-d3e7-416d-8c80-82dc4dd77026)

**Comment by arjxn-py** [comment]
Would just making the default diameter of sphere 1 work here?

**Comment by martinRenou** [comment]
Indeed! We have the same issue with Torus
