### ISSUE TITLE
Proposed UX for the exploded view

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#489]
I propose to make the exploded view toolbar button a toggle.

The exploded view factor number input could be set either in a separate dropdown in the toolbar (at first), or in a text input overlayed on the view.

On a separate note, maybe there should be a visual indication in the view that the exploded view is not the normal position of objects - and how to leave this view, in case someone does not know how to set it back to normal.

**Comment by martinRenou** [comment]
Closing as duplicate of #443
