### ISSUE TITLE
Clip plane color is not visible on dark background

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#500]
It seems that the clip plane color is not quite visible on dark backgrounds. It is still somewhat visible, so it is probably just a color choice issue.

![Image](https://github.com/user-attachments/assets/eb22e536-78d1-4c10-92e9-f694ee7d89d4)

**Comment by martinRenou** [comment]
Adding it to the 3.0.0 milestone.

Right now the clip plane is `color: 'black', opacity: 0.2`. Maybe the color should come from a CSS variable instead, and react on theme change.
