### ISSUE TITLE
Build some nice examples to showcase JupyterCAD features

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#502]
Today the examples directory is a bit poor: https://github.com/jupytercad/JupyterCAD/tree/main/examples

We should build some nice examples to show off a bit: 
- planetary cogs (semi hard)
- "JupyterCAD" written in 3D based of only primitives (hard?)

Additionally we should probably move `test.jcad` under the `ui-tests` directory instead of keeping it in the `examples` one.

**Comment by SylvainCorlay** [comment]
The basic `test.jcad` in the example directory does not do justice to JupyterCAD indeed.

**Comment by SylvainCorlay** [comment]
Closing as completed - also since 3.0 is out.
