### ISSUE TITLE
After applying an operator the boundinx boxes of the inputs are still visible

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#526]
After applying an operator the boundinx boxes of the inputs are still visible:

https://github.com/user-attachments/assets/2126212d-9a65-4c9f-8d76-d7a8e9e10edc

I expected this not behave that way after putting the bounding box as part of the mesh group in https://github.com/jupytercad/JupyterCAD/pull/521, but it does.

Maybe we're not setting the `visible` property on the whole group.

**Comment by martinRenou** [comment]
Oh wait I guess it is the combination of two issues.

- I see the two inputs are still selected on the left panel: **the generated output should probably be selected after the operator is done instead**
- We should not create/show a bounding box for an object that's not visible

**Comment by arjxn-py** [comment]
thanks for opening this @martinRenou, the explanation helps already and will look more into it
