### ISSUE TITLE
Cannot download JCAD file from file browser in JupyterCAD (it works with other file types)

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#544]
Testing from JupyterLite, this results in the following error in the JS console.

```
Uncaught (in promise) Error: Content whose type is "jcad" cannot be downloaded
    at u (index.js:127:23)
    at async index.js:170:34
```

**Comment by martinRenou** [comment]
It seems the (hidden) exception is `"Error: Content whose type is "jcad" cannot be downloaded"` coming from here https://github.com/jupyterlite/jupyterlite/blob/main/packages/application-extension/src/index.tsx#L209

I will see to fix it

**Comment by martinRenou** [comment]
https://github.com/jupyterlite/jupyterlite/pull/1521 Should fix it

**Comment by arjxn-py** [comment]
Thanks @martinRenou

**Comment by SylvainCorlay** [comment]
Should we redeploy with JupyterLite v0.4.4 and close this issue @martinRenou ?

**Comment by martinRenou** [comment]
Latest deployment uses jupyterlite-core 0.4.4 and I can confirm this is fixed and I can now download `.jcad` files after edits!
