### ISSUE TITLE
Selection state seems to jump between tree and mainview

### ISSUE THREAD

**Issue by martinRenou** [jupytercad/JupyterCAD#560]
I've seen this happen many times in my last couple of times playing with jupytercad:

https://github.com/user-attachments/assets/5e50cfca-8e0f-45e1-ad28-9ccfa03c6daf

**Comment by trungleduc** [comment]
I also get hit by this issue sometime but cannot find a reliable way to reproduce it.

**Comment by arjxn-py** [comment]
Potential culprit:

https://github.com/jupytercad/JupyterCAD/blob/4f7c1fc5752624155257d9a74d8ebb5fa7d721fe/packages/base/src/3dview/mainview.tsx#L1179-L1181

**Comment by SylvainCorlay** [comment]
I have not been able to reproduce this issue.
