### ISSUE TITLE
Use UUID instead of name to filter objects

### ISSUE THREAD

**Issue by arjxn-py** [jupytercad/JupyterCAD#567]
Relying on the name is a bit of a poor choice. We should have UUIDs for object names on the long term to prevent any issue.

_Originally posted by @martinRenou in https://github.com/jupytercad/JupyterCAD/pull/564#discussion_r1831287573_

**Comment by martinRenou** [comment]
Actually this may be already open with this issue #200. I will add a comment there. Thanks @arjxn-py !
