### ISSUE TITLE
File name not updated upon change in the side panel

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#586]
When renaming a file, the side panel does not update.

![Image](https://github.com/user-attachments/assets/5c8e7c8f-10f4-4f05-a02d-064f9aef368b)

**Comment by martinRenou** [comment]
How about we don't put the filename here? 

It's taking up space, not giving any more information that we already have.

**Comment by martinRenou** [comment]
Right. Though we don't do this for notebooks with the debugger nor the cell metadata editor.

**Comment by trungleduc** [comment]
>  Though we don't do this for notebooks with the debugger

we do

![Image](https://github.com/user-attachments/assets/1e51f00e-0f60-4b78-8010-ea0a815fc696)

**Comment by martinRenou** [comment]
Ah right! It needs to be started before we show the Notebook name.
