### ISSUE TITLE
Rotation transforms not working with the Gear example

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#651]
The object appears to render, but appears in the original position after releasing the mouse.

**Comment by martinRenou** [comment]
As discussed internally, since that file was exported using jupytercad-freecad, this may be due to jupytercad-freecad not respecting the JupyterCAD schemas. We should fix it there in jupytercad-freecad.

For now we can either remove that file from the examples directory or live with it.

**Comment by martinRenou** [comment]
It is actually a JupyterCAD issue in our OpenCascade worker which is not placing the object properly
