### ISSUE TITLE
`jupyterlab.browser_check` is disabled

### ISSUE THREAD

**Issue by trungleduc** [jupytercad/JupyterCAD#78]
`browser_check` is broken with the changes in jupyter_server 2.0.2 (https://github.com/jupyter-server/jupyter_server/issues/1143). It is disabled in our CI and should be re-enabled once it's fixed upstream.

Related PR https://github.com/QuantStack/jupytercad/pull/77

**Comment by arjxn-py** [comment]
@trungleduc Can it be re-enabled as the upstream issue is closed as completed?

**Comment by arjxn-py** [comment]
I'd be happy to open up a quick PR for that & See if CI works nicely?

**Comment by trungleduc** [comment]
yes, it would be great!
